# https://github.com/microsoft/vscode-dev-containers/blob/main/containers/docker-from-docker-compose/.devcontainer/docker-compose.yml
version: '3'

services:
  kind-dev:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Kubernetes公式バージョン（https://kubernetes.io/ja/releases/）＋それに対応するOSSのバージョンを確認
        # 20250515最新のKubernetes 1.33.1に合わせて実装
        - KIND_VERSION=0.28.0
        - KUBECTL_VERSION=1.33.0
    volumes:
      - kind_dev_volume:/workspaces
    # docker操作にはカーネルの強い操作権限が必要（コンテナ自体はホストカーネルを使用するので、devContainerに権限が必要）
    privileged: true
    # コンテナが停止しないようにする
    command: sleep infinity

volumes:
  kind_dev_volume: